### ISSUE TITLE
Stack direction is reversed

### ISSUE THREAD

**Issue by theBrianCui** [xsznix/js-y86#1]
The "top of the stack" is traditionally drawn on the bottom with decreasing values, while the "bottom of the stack" is drawn on the top with increasing values. The simulator has it backwards though - smaller addresses are found near the top of the page, while larger addresses are at the bottom. It'd be nice to see the stack in its current form in the simulator reversed, or at least have an option to do so.

**Comment by xsznix** [comment]
Really? I've seen it both ways. See:

https://y86tutoring.files.wordpress.com/2012/10/caller-callee.png
https://stackoverflow.com/questions/1023208/do-i-understand-the-stack-properly-in-this-y86-assembly-code

To make it go up, you'd have to initialise the memory pane scrolled all the way to the bottom and add more memory word lines to the top of the memory if the user scrolls up. It's doable, but I don't think I can justify the effort—going that direction also runs contrary to the direction of the 'memory' in the object code and the source code, where corresponding addresses grow as the code goes down the page. And the memory pane doesn't only show you the stack, but the rest of memory, as well.

You're free to submit a PR if you'd like to work on it, though.
