### ISSUE TITLE
Y86 instructions

### ISSUE THREAD

**Issue by amshaffie** [xsznix/js-y86#14]
I didn't find an access to the %r8d register for example. why not all the registers appears in your implementation

**Comment by amshaffie** [comment]
Also why irmovq instruction doesn't work ? I expect that this should be a Y86 instructions as I understood from the following link
https://csit.kutztown.edu/~schwesin/fall21/csc235/lectures/Instruction_Set_Architecture.html

**Comment by xsznix** [comment]
CS:APP switched to a 64-bit version of Y86 a few years ago. This repo is for the older, 32-bit Y86. For your class work, you'll want to use one of the 64-bit forks of this app such as this one: https://boginw.github.io/js-y86-64/
