### ISSUE TITLE
Stack display not working in Firefox

### ISSUE THREAD

**Issue by CuriousG102** [xsznix/js-y86#2]
Hello! Great job on this project. I've been using it for the same CS class you're in and it's a wonderful interface for testing our programs. There's a minor issue with your display in Firefox on my Mac, which prevents me from using it in that browser. The issue doesn't present itself in Safari. 
![issue image](https://cloud.githubusercontent.com/assets/5168909/6403848/e7ae6c86-bdd7-11e4-8385-3afc65e0e675.jpg)

The image should show it all. When ebp and esp jump down, there is not printed output for them.

This may be a case of Firefox not supporting some JS feature that you utilize, and Safari doing so. I don't have time today to dig into your source. In any case I thought I'd let you know!

**Comment by xsznix** [comment]
Heh, that's weird. I'll look into that this weekend. In the meantime, can you consider using Chrome, Safari, or Opera instead?

**Comment by CuriousG102** [comment]
I already am! Believe me I understand the frustration of the current state of cross-browser compatibility.
