### ISSUE TITLE
EBP and ESP pointers are off row in higher memory locations in Safari

### ISSUE THREAD

**Issue by CuriousG102** [xsznix/js-y86#4]
See here: EBP and ESP between rows, below the row that they should be pointing to.
![issue image](https://cloud.githubusercontent.com/assets/5168909/6408935/14ed3d7c-be22-11e4-9e86-f76b40d0751b.jpg)

**Comment by xsznix** [comment]
What version of Safari do you have? Also, did your stack pointers get misaligned? My code will render your ebp/esp there if they point te 0x0ff6.

**Comment by CuriousG102** [comment]
My stack pointers were misaligned... Started at 0xfff rather than 0xffc on accident.... Whoops.

**Comment by CuriousG102** [comment]
I'm curious as to why my programs didn't blow up.

**Comment by xsznix** [comment]
Can you paste a small program that causes this behavior?

**Comment by xsznix** [comment]
Ah, that's what I thought. You'll still read the values from the memory at the right place, it just won't be word-aligned. I'm not sure if addressing on non-word-boundaries actually works in the official simulator…

**Comment by CuriousG102** [comment]
It does!
