### ISSUE TITLE
Error in Padding

### ISSUE THREAD

**Issue by jgluck** [xsznix/js-y86#5]
@xsznix Ran into this in my fork (for a class I TA)

https://github.com/xsznix/js-y86/blob/master/js/assem.js#L4

Check out what happens when you attempt the following instruction:

```
irmovl 0x1000, %esp
```

**Comment by jgluck** [comment]
You can solve the problem by either converting the number to bigendian before passing it to padhex (and then back), or write a padlittleendian hex function.

**Comment by xsznix** [comment]
Thanks for the report!

I suppose you and/or your students have come across this while learning Y86. Glad to know it may be useful after my current class is done with it.
