### ISSUE TITLE
Bug with conditional move

### ISSUE THREAD

**Issue by nraiha** [xsznix/js-y86#9]
Is there a bug with cmovl? (cmovq seems to be working, doing the same cmovl should do.)
As far as I know conditional moves should be the same in y86 and y86-64. So shouldn't cmovq be cmovl?

**Comment by xsznix** [comment]
Pinging @boginw – I think it's your fork that does that.

See lam2mo/js-y86-64@02875c9bf524fbe62d0e3f6f3f31693a1dc13f53 and lam2mo/js-y86-64@f41665f32a67a5d88bd24ba650afe9d282d11040 for a fix.

**Comment by boginw** [comment]
Just looked it up in the book, and you seem to be right @nraiha. I've merged @Iam2mo's fork into mine, so there won't be any confusion in the future. Thanks for pointing it out 👍
